base_map = {"A": 69, "T": 64, "G": 67, "C": 60}

# Mappings from Edward et al 2021 (Table 1) - PMID: 34556048
amino_acids = {
    'F': 50,
    'M': 51,
    'I': 52,
    'L': 53,
    'V': 54,
    'C': 55,
    'W': 56,
    'A': 57,
    'T': 58,
    'G': 59,
    'S': 60,
    'P': 61,
    'Y': 62,
    'H': 65,
    'Q': 66,
    'N': 67,
    'E': 71,
    'K': 72,
    'D': 73,
    'R': 77,
}

# Codon to amino acid mapping, built out from the above
codons = {
    'TTT': {'name': 'Phenylalanine', 'symbol': 'F', 'midi': 50},
    'TTC': {'name': 'Phenylalanine', 'symbol': 'F', 'midi': 50},
    'TTA': {'name': 'Leucine', 'symbol': 'L', 'midi': 53},
    'TTG': {'name': 'Leucine', 'symbol': 'L', 'midi': 53},
    'TCT': {'name': 'Serine', 'symbol': 'S', 'midi': 60},
    'TCC': {'name': 'Serine', 'symbol': 'S', 'midi': 60},
    'TCA': {'name': 'Serine', 'symbol': 'S', 'midi': 60},
    'TCG': {'name': 'Serine', 'symbol': 'S', 'midi': 60},
    'TAT': {'name': 'Tyrosine', 'symbol': 'Y', 'midi': 62},
    'TAC': {'name': 'Tyrosine', 'symbol': 'Y', 'midi': 62},
    'TAA': {'name': 'Stop', 'symbol': '*', 'midi': None},
    'TAG': {'name': 'Stop', 'symbol': '*', 'midi': None},
    'TGT': {'name': 'Cysteine', 'symbol': 'C', 'midi': 55},
    'TGC': {'name': 'Cysteine', 'symbol': 'C', 'midi': 55},
    'TGA': {'name': 'Stop', 'symbol': '*', 'midi': None},
    'TGG': {'name': 'Tryptophan', 'symbol': 'W', 'midi': 56},
    'CTT': {'name': 'Leucine', 'symbol': 'L', 'midi': 53},
    'CTC': {'name': 'Leucine', 'symbol': 'L', 'midi': 53},
    'CTA': {'name': 'Leucine', 'symbol': 'L', 'midi': 53},
    'CTG': {'name': 'Leucine', 'symbol': 'L', 'midi': 53},
    'CCT': {'name': 'Proline', 'symbol': 'P', 'midi': 61},
    'CCC': {'name': 'Proline', 'symbol': 'P', 'midi': 61},
    'CCA': {'name': 'Proline', 'symbol': 'P', 'midi': 61},
    'CCG': {'name': 'Proline', 'symbol': 'P', 'midi': 61},
    'CAT': {'name': 'Histidine', 'symbol': 'H', 'midi': 65},
    'CAC': {'name': 'Histidine', 'symbol': 'H', 'midi': 65},
    'CAA': {'name': 'Glutamine', 'symbol': 'Q', 'midi': 66},
    'CAG': {'name': 'Glutamine', 'symbol': 'Q', 'midi': 66},
    'CGT': {'name': 'Arginine', 'symbol': 'R', 'midi': 77},
    'CGC': {'name': 'Arginine', 'symbol': 'R', 'midi': 77},
    'CGA': {'name': 'Arginine', 'symbol': 'R', 'midi': 77},
    'CGG': {'name': 'Arginine', 'symbol': 'R', 'midi': 77},
    'ATT': {'name': 'Isoleucine', 'symbol': 'I', 'midi': 52},
    'ATC': {'name': 'Isoleucine', 'symbol': 'I', 'midi': 52},
    'ATA': {'name': 'Isoleucine', 'symbol': 'I', 'midi': 52},
    'ATG': {'name': 'Methionine', 'symbol': 'M', 'midi': 51},
    'ACT': {'name': 'Threonine', 'symbol': 'T', 'midi': 58},
    'ACC': {'name': 'Threonine', 'symbol': 'T', 'midi': 58},
    'ACA': {'name': 'Threonine', 'symbol': 'T', 'midi': 58},
    'ACG': {'name': 'Threonine', 'symbol': 'T', 'midi': 58},
    'AAT': {'name': 'Asparagine', 'symbol': 'N', 'midi': 67},
    'AAC': {'name': 'Asparagine', 'symbol': 'N', 'midi': 67},
    'AAA': {'name': 'Lysine', 'symbol': 'K', 'midi': 72},
    'AAG': {'name': 'Lysine', 'symbol': 'K', 'midi': 72},
    'AGT': {'name': 'Serine', 'symbol': 'S', 'midi': 60},
    'AGC': {'name': 'Serine', 'symbol': 'S', 'midi': 60},
    'AGA': {'name': 'Arginine', 'symbol': 'R', 'midi': 77},
    'AGG': {'name': 'Arginine', 'symbol': 'R', 'midi': 77},
    'GTT': {'name': 'Valine', 'symbol': 'V', 'midi': 54},
    'GTC': {'name': 'Valine', 'symbol': 'V', 'midi': 54},
    'GTA': {'name': 'Valine', 'symbol': 'V', 'midi': 54},
    'GTG': {'name': 'Valine', 'symbol': 'V', 'midi': 54},
    'GCT': {'name': 'Alanine', 'symbol': 'A', 'midi': 57},
    'GCC': {'name': 'Alanine', 'symbol': 'A', 'midi': 57},
    'GCA': {'name': 'Alanine', 'symbol': 'A', 'midi': 57},
    'GCG': {'name': 'Alanine', 'symbol': 'A', 'midi': 57},
    'GAT': {'name': 'Aspartate', 'symbol': 'D', 'midi': 73},
    'GAC': {'name': 'Aspartate', 'symbol': 'D', 'midi': 73},
    'GAA': {'name': 'Glutamate', 'symbol': 'E', 'midi': 71},
    'GAG': {'name': 'Glutamate', 'symbol': 'E', 'midi': 71},
    'GGT': {'name': 'Glycine', 'symbol': 'G', 'midi': 59},
    'GGC': {'name': 'Glycine', 'symbol': 'G', 'midi': 59},
    'GGA': {'name': 'Glycine', 'symbol': 'G', 'midi': 59},
    'GGG': {'name': 'Glycine', 'symbol': 'G', 'midi': 59},
}