base_map = {"A": 69, "T": 64, "G": 67, "C": 60}

# Mappings from Edward et al 2021 (Table 1) - PMID: 34556048
amino_acids = {
    'F': 50,
    'M': 51,
    'I': 52,
    'L': 53,
    'V': 54,
    'C': 55,
    'W': 56,
    'A': 57,
    'T': 58,
    'G': 59,
    'S': 60,
    'P': 61,
    'Y': 62,
    'H': 65,
    'Q': 66,
    'N': 67,
    'E': 71,
    'K': 72,
    'D': 73,
    'R': 77,
}

# Codon to amino acid mapping, built out from the above
# Edwards et al
codons = {
    'TTT': {'name': 'Phenylalanine', 'symbol': 'F', 'midi': 50},
    'TTC': {'name': 'Phenylalanine', 'symbol': 'F', 'midi': 50},
    'TTA': {'name': 'Leucine', 'symbol': 'L', 'midi': 53},
    'TTG': {'name': 'Leucine', 'symbol': 'L', 'midi': 53},
    'TCT': {'name': 'Serine', 'symbol': 'S', 'midi': 60},
    'TCC': {'name': 'Serine', 'symbol': 'S', 'midi': 60},
    'TCA': {'name': 'Serine', 'symbol': 'S', 'midi': 60},
    'TCG': {'name': 'Serine', 'symbol': 'S', 'midi': 60},
    'TAT': {'name': 'Tyrosine', 'symbol': 'Y', 'midi': 62},
    'TAC': {'name': 'Tyrosine', 'symbol': 'Y', 'midi': 62},
    'TAA': {'name': 'Stop', 'symbol': '*', 'midi': None},
    'TAG': {'name': 'Stop', 'symbol': '*', 'midi': None},
    'TGT': {'name': 'Cysteine', 'symbol': 'C', 'midi': 55},
    'TGC': {'name': 'Cysteine', 'symbol': 'C', 'midi': 55},
    'TGA': {'name': 'Stop', 'symbol': '*', 'midi': None},
    'TGG': {'name': 'Tryptophan', 'symbol': 'W', 'midi': 56},
    'CTT': {'name': 'Leucine', 'symbol': 'L', 'midi': 53},
    'CTC': {'name': 'Leucine', 'symbol': 'L', 'midi': 53},
    'CTA': {'name': 'Leucine', 'symbol': 'L', 'midi': 53},
    'CTG': {'name': 'Leucine', 'symbol': 'L', 'midi': 53},
    'CCT': {'name': 'Proline', 'symbol': 'P', 'midi': 61},
    'CCC': {'name': 'Proline', 'symbol': 'P', 'midi': 61},
    'CCA': {'name': 'Proline', 'symbol': 'P', 'midi': 61},
    'CCG': {'name': 'Proline', 'symbol': 'P', 'midi': 61},
    'CAT': {'name': 'Histidine', 'symbol': 'H', 'midi': 65},
    'CAC': {'name': 'Histidine', 'symbol': 'H', 'midi': 65},
    'CAA': {'name': 'Glutamine', 'symbol': 'Q', 'midi': 66},
    'CAG': {'name': 'Glutamine', 'symbol': 'Q', 'midi': 66},
    'CGT': {'name': 'Arginine', 'symbol': 'R', 'midi': 77},
    'CGC': {'name': 'Arginine', 'symbol': 'R', 'midi': 77},
    'CGA': {'name': 'Arginine', 'symbol': 'R', 'midi': 77},
    'CGG': {'name': 'Arginine', 'symbol': 'R', 'midi': 77},
    'ATT': {'name': 'Isoleucine', 'symbol': 'I', 'midi': 52},
    'ATC': {'name': 'Isoleucine', 'symbol': 'I', 'midi': 52},
    'ATA': {'name': 'Isoleucine', 'symbol': 'I', 'midi': 52},
    'ATG': {'name': 'Methionine', 'symbol': 'M', 'midi': 51},
    'ACT': {'name': 'Threonine', 'symbol': 'T', 'midi': 58},
    'ACC': {'name': 'Threonine', 'symbol': 'T', 'midi': 58},
    'ACA': {'name': 'Threonine', 'symbol': 'T', 'midi': 58},
    'ACG': {'name': 'Threonine', 'symbol': 'T', 'midi': 58},
    'AAT': {'name': 'Asparagine', 'symbol': 'N', 'midi': 67},
    'AAC': {'name': 'Asparagine', 'symbol': 'N', 'midi': 67},
    'AAA': {'name': 'Lysine', 'symbol': 'K', 'midi': 72},
    'AAG': {'name': 'Lysine', 'symbol': 'K', 'midi': 72},
    'AGT': {'name': 'Serine', 'symbol': 'S', 'midi': 60},
    'AGC': {'name': 'Serine', 'symbol': 'S', 'midi': 60},
    'AGA': {'name': 'Arginine', 'symbol': 'R', 'midi': 77},
    'AGG': {'name': 'Arginine', 'symbol': 'R', 'midi': 77},
    'GTT': {'name': 'Valine', 'symbol': 'V', 'midi': 54},
    'GTC': {'name': 'Valine', 'symbol': 'V', 'midi': 54},
    'GTA': {'name': 'Valine', 'symbol': 'V', 'midi': 54},
    'GTG': {'name': 'Valine', 'symbol': 'V', 'midi': 54},
    'GCT': {'name': 'Alanine', 'symbol': 'A', 'midi': 57},
    'GCC': {'name': 'Alanine', 'symbol': 'A', 'midi': 57},
    'GCA': {'name': 'Alanine', 'symbol': 'A', 'midi': 57},
    'GCG': {'name': 'Alanine', 'symbol': 'A', 'midi': 57},
    'GAT': {'name': 'Aspartate', 'symbol': 'D', 'midi': 73},
    'GAC': {'name': 'Aspartate', 'symbol': 'D', 'midi': 73},
    'GAA': {'name': 'Glutamate', 'symbol': 'E', 'midi': 71},
    'GAG': {'name': 'Glutamate', 'symbol': 'E', 'midi': 71},
    'GGT': {'name': 'Glycine', 'symbol': 'G', 'midi': 59},
    'GGC': {'name': 'Glycine', 'symbol': 'G', 'midi': 59},
    'GGA': {'name': 'Glycine', 'symbol': 'G', 'midi': 59},
    'GGG': {'name': 'Glycine', 'symbol': 'G', 'midi': 59},
}

# # Alphabetical by amino acid
# codons = {
#     'TTT': {'name': 'Phenylalanine', 'symbol': 'F', 'midi': 64},
#     'TTC': {'name': 'Phenylalanine', 'symbol': 'F', 'midi': 64},
#     'TTA': {'name': 'Leucine', 'symbol': 'L', 'midi': 69},
#     'TTG': {'name': 'Leucine', 'symbol': 'L', 'midi': 69},
#     'TCT': {'name': 'Serine', 'symbol': 'S', 'midi': 75},
#     'TCC': {'name': 'Serine', 'symbol': 'S', 'midi': 75},
#     'TCA': {'name': 'Serine', 'symbol': 'S', 'midi': 75},
#     'TCG': {'name': 'Serine', 'symbol': 'S', 'midi': 75},
#     'TAT': {'name': 'Tyrosine', 'symbol': 'Y', 'midi': 79},
#     'TAC': {'name': 'Tyrosine', 'symbol': 'Y', 'midi': 79},
#     'TAA': {'name': 'Stop', 'symbol': '*', 'midi': None},
#     'TAG': {'name': 'Stop', 'symbol': '*', 'midi': None},
#     'TGT': {'name': 'Cysteine', 'symbol': 'C', 'midi': 61},
#     'TGC': {'name': 'Cysteine', 'symbol': 'C', 'midi': 61},
#     'TGA': {'name': 'Stop', 'symbol': '*', 'midi': None},
#     'TGG': {'name': 'Tryptophan', 'symbol': 'W', 'midi': 78},
#     'CTT': {'name': 'Leucine', 'symbol': 'L', 'midi': 69},
#     'CTC': {'name': 'Leucine', 'symbol': 'L', 'midi': 69},
#     'CTA': {'name': 'Leucine', 'symbol': 'L', 'midi': 69},
#     'CTG': {'name': 'Leucine', 'symbol': 'L', 'midi': 69},
#     'CCT': {'name': 'Proline', 'symbol': 'P', 'midi': 72},
#     'CCC': {'name': 'Proline', 'symbol': 'P', 'midi': 72},
#     'CCA': {'name': 'Proline', 'symbol': 'P', 'midi': 72},
#     'CCG': {'name': 'Proline', 'symbol': 'P', 'midi': 72},
#     'CAT': {'name': 'Histidine', 'symbol': 'H', 'midi': 66},
#     'CAC': {'name': 'Histidine', 'symbol': 'H', 'midi': 66},
#     'CAA': {'name': 'Glutamine', 'symbol': 'Q', 'midi': 73},
#     'CAG': {'name': 'Glutamine', 'symbol': 'Q', 'midi': 73},
#     'CGT': {'name': 'Arginine', 'symbol': 'R', 'midi': 74},
#     'CGC': {'name': 'Arginine', 'symbol': 'R', 'midi': 74},
#     'CGA': {'name': 'Arginine', 'symbol': 'R', 'midi': 74},
#     'CGG': {'name': 'Arginine', 'symbol': 'R', 'midi': 74},
#     'ATT': {'name': 'Isoleucine', 'symbol': 'I', 'midi': 67},
#     'ATC': {'name': 'Isoleucine', 'symbol': 'I', 'midi': 67},
#     'ATA': {'name': 'Isoleucine', 'symbol': 'I', 'midi': 67},
#     'ATG': {'name': 'Methionine', 'symbol': 'M', 'midi': 70},
#     'ACT': {'name': 'Threonine', 'symbol': 'T', 'midi': 76},
#     'ACC': {'name': 'Threonine', 'symbol': 'T', 'midi': 76},
#     'ACA': {'name': 'Threonine', 'symbol': 'T', 'midi': 76},
#     'ACG': {'name': 'Threonine', 'symbol': 'T', 'midi': 76},
#     'AAT': {'name': 'Asparagine', 'symbol': 'N', 'midi': 71},
#     'AAC': {'name': 'Asparagine', 'symbol': 'N', 'midi': 71},
#     'AAA': {'name': 'Lysine', 'symbol': 'K', 'midi': 68},
#     'AAG': {'name': 'Lysine', 'symbol': 'K', 'midi': 68},
#     'AGT': {'name': 'Serine', 'symbol': 'S', 'midi': 75},
#     'AGC': {'name': 'Serine', 'symbol': 'S', 'midi': 75},
#     'AGA': {'name': 'Arginine', 'symbol': 'R', 'midi': 74},
#     'AGG': {'name': 'Arginine', 'symbol': 'R', 'midi': 74},
#     'GTT': {'name': 'Valine', 'symbol': 'V', 'midi': 77},
#     'GTC': {'name': 'Valine', 'symbol': 'V', 'midi': 77},
#     'GTA': {'name': 'Valine', 'symbol': 'V', 'midi': 77},
#     'GTG': {'name': 'Valine', 'symbol': 'V', 'midi': 77},
#     'GCT': {'name': 'Alanine', 'symbol': 'A', 'midi': 60},
#     'GCC': {'name': 'Alanine', 'symbol': 'A', 'midi': 60},
#     'GCA': {'name': 'Alanine', 'symbol': 'A', 'midi': 60},
#     'GCG': {'name': 'Alanine', 'symbol': 'A', 'midi': 60},
#     'GAT': {'name': 'Aspartate', 'symbol': 'D', 'midi': 62},
#     'GAC': {'name': 'Aspartate', 'symbol': 'D', 'midi': 62},
#     'GAA': {'name': 'Glutamate', 'symbol': 'E', 'midi': 63},
#     'GAG': {'name': 'Glutamate', 'symbol': 'E', 'midi': 63},
#     'GGT': {'name': 'Glycine', 'symbol': 'G', 'midi': 65},
#     'GGC': {'name': 'Glycine', 'symbol': 'G', 'midi': 65},
#     'GGA': {'name': 'Glycine', 'symbol': 'G', 'midi': 65},
#     'GGG': {'name': 'Glycine', 'symbol': 'G', 'midi': 65},
# }

# By AA mol weight
# codons = {
#     'TTT': {'name': 'Phenylalanine', 'symbol': 'F', 'midi': 76},
#     'TTC': {'name': 'Phenylalanine', 'symbol': 'F', 'midi': 76},
#     'TTA': {'name': 'Leucine', 'symbol': 'L', 'midi': 68},
#     'TTG': {'name': 'Leucine', 'symbol': 'L', 'midi': 68},
#     'TCT': {'name': 'Serine', 'symbol': 'S', 'midi': 62},
#     'TCC': {'name': 'Serine', 'symbol': 'S', 'midi': 62},
#     'TCA': {'name': 'Serine', 'symbol': 'S', 'midi': 62},
#     'TCG': {'name': 'Serine', 'symbol': 'S', 'midi': 62},
#     'TAT': {'name': 'Tyrosine', 'symbol': 'Y', 'midi': 78},
#     'TAC': {'name': 'Tyrosine', 'symbol': 'Y', 'midi': 78},
#     'TAA': {'name': 'Stop', 'symbol': '*', 'midi': None},
#     'TAG': {'name': 'Stop', 'symbol': '*', 'midi': None},
#     'TGT': {'name': 'Cysteine', 'symbol': 'C', 'midi': 66},
#     'TGC': {'name': 'Cysteine', 'symbol': 'C', 'midi': 66},
#     'TGA': {'name': 'Stop', 'symbol': '*', 'midi': None},
#     'TGG': {'name': 'Tryptophan', 'symbol': 'W', 'midi': 79},
#     'CTT': {'name': 'Leucine', 'symbol': 'L', 'midi': 68},
#     'CTC': {'name': 'Leucine', 'symbol': 'L', 'midi': 68},
#     'CTA': {'name': 'Leucine', 'symbol': 'L', 'midi': 68},
#     'CTG': {'name': 'Leucine', 'symbol': 'L', 'midi': 68},
#     'CCT': {'name': 'Proline', 'symbol': 'P', 'midi': 63},
#     'CCC': {'name': 'Proline', 'symbol': 'P', 'midi': 63},
#     'CCA': {'name': 'Proline', 'symbol': 'P', 'midi': 63},
#     'CCG': {'name': 'Proline', 'symbol': 'P', 'midi': 63},
#     'CAT': {'name': 'Histidine', 'symbol': 'H', 'midi': 75},
#     'CAC': {'name': 'Histidine', 'symbol': 'H', 'midi': 75},
#     'CAA': {'name': 'Glutamine', 'symbol': 'Q', 'midi': 71},
#     'CAG': {'name': 'Glutamine', 'symbol': 'Q', 'midi': 71},
#     'CGT': {'name': 'Arginine', 'symbol': 'R', 'midi': 77},
#     'CGC': {'name': 'Arginine', 'symbol': 'R', 'midi': 77},
#     'CGA': {'name': 'Arginine', 'symbol': 'R', 'midi': 77},
#     'CGG': {'name': 'Arginine', 'symbol': 'R', 'midi': 77},
#     'ATT': {'name': 'Isoleucine', 'symbol': 'I', 'midi': 67},
#     'ATC': {'name': 'Isoleucine', 'symbol': 'I', 'midi': 67},
#     'ATA': {'name': 'Isoleucine', 'symbol': 'I', 'midi': 67},
#     'ATG': {'name': 'Methionine', 'symbol': 'M', 'midi': 74},
#     'ACT': {'name': 'Threonine', 'symbol': 'T', 'midi': 65},
#     'ACC': {'name': 'Threonine', 'symbol': 'T', 'midi': 65},
#     'ACA': {'name': 'Threonine', 'symbol': 'T', 'midi': 65},
#     'ACG': {'name': 'Threonine', 'symbol': 'T', 'midi': 65},
#     'AAT': {'name': 'Asparagine', 'symbol': 'N', 'midi': 69},
#     'AAC': {'name': 'Asparagine', 'symbol': 'N', 'midi': 69},
#     'AAA': {'name': 'Lysine', 'symbol': 'K', 'midi': 72},
#     'AAG': {'name': 'Lysine', 'symbol': 'K', 'midi': 72},
#     'AGT': {'name': 'Serine', 'symbol': 'S', 'midi': 62},
#     'AGC': {'name': 'Serine', 'symbol': 'S', 'midi': 62},
#     'AGA': {'name': 'Arginine', 'symbol': 'R', 'midi': 77},
#     'AGG': {'name': 'Arginine', 'symbol': 'R', 'midi': 77},
#     'GTT': {'name': 'Valine', 'symbol': 'V', 'midi': 64},
#     'GTC': {'name': 'Valine', 'symbol': 'V', 'midi': 64},
#     'GTA': {'name': 'Valine', 'symbol': 'V', 'midi': 64},
#     'GTG': {'name': 'Valine', 'symbol': 'V', 'midi': 64},
#     'GCT': {'name': 'Alanine', 'symbol': 'A', 'midi': 61},
#     'GCC': {'name': 'Alanine', 'symbol': 'A', 'midi': 61},
#     'GCA': {'name': 'Alanine', 'symbol': 'A', 'midi': 61},
#     'GCG': {'name': 'Alanine', 'symbol': 'A', 'midi': 61},
#     'GAT': {'name': 'Aspartate', 'symbol': 'D', 'midi': 70},
#     'GAC': {'name': 'Aspartate', 'symbol': 'D', 'midi': 70},
#     'GAA': {'name': 'Glutamate', 'symbol': 'E', 'midi': 73},
#     'GAG': {'name': 'Glutamate', 'symbol': 'E', 'midi': 73},
#     'GGT': {'name': 'Glycine', 'symbol': 'G', 'midi': 60},
#     'GGC': {'name': 'Glycine', 'symbol': 'G', 'midi': 60},
#     'GGA': {'name': 'Glycine', 'symbol': 'G', 'midi': 60},
#     'GGG': {'name': 'Glycine', 'symbol': 'G', 'midi': 60},
# }

# codons = {
#     'TTT': {'name': 'Phenylalanine', 'symbol': 'F', 'midi': 67},
#     'TTC': {'name': 'Phenylalanine', 'symbol': 'F', 'midi': 67},
#     'TTA': {'name': 'Leucine', 'symbol': 'L', 'midi': 62},
#     'TTG': {'name': 'Leucine', 'symbol': 'L', 'midi': 62},
#     'TCT': {'name': 'Serine', 'symbol': 'S', 'midi': 62},
#     'TCC': {'name': 'Serine', 'symbol': 'S', 'midi': 62},
#     'TCA': {'name': 'Serine', 'symbol': 'S', 'midi': 62},
#     'TCG': {'name': 'Serine', 'symbol': 'S', 'midi': 62},
#     'TAT': {'name': 'Tyrosine', 'symbol': 'Y', 'midi': 67},
#     'TAC': {'name': 'Tyrosine', 'symbol': 'Y', 'midi': 67},
#     'TAA': {'name': 'Stop', 'symbol': '*', 'midi': None},
#     'TAG': {'name': 'Stop', 'symbol': '*', 'midi': None},
#     'TGT': {'name': 'Cysteine', 'symbol': 'C', 'midi': 71},
#     'TGC': {'name': 'Cysteine', 'symbol': 'C', 'midi': 71},
#     'TGA': {'name': 'Stop', 'symbol': '*', 'midi': None},
#     'TGG': {'name': 'Tryptophan', 'symbol': 'W', 'midi': 64},
#     'CTT': {'name': 'Leucine', 'symbol': 'L', 'midi': 62},
#     'CTC': {'name': 'Leucine', 'symbol': 'L', 'midi': 62},
#     'CTA': {'name': 'Leucine', 'symbol': 'L', 'midi': 62},
#     'CTG': {'name': 'Leucine', 'symbol': 'L', 'midi': 62},
#     'CCT': {'name': 'Proline', 'symbol': 'P', 'midi': 71},
#     'CCC': {'name': 'Proline', 'symbol': 'P', 'midi': 71},
#     'CCA': {'name': 'Proline', 'symbol': 'P', 'midi': 71},
#     'CCG': {'name': 'Proline', 'symbol': 'P', 'midi': 71},
#     'CAT': {'name': 'Histidine', 'symbol': 'H', 'midi': 76},
#     'CAC': {'name': 'Histidine', 'symbol': 'H', 'midi': 76},
#     'CAA': {'name': 'Glutamine', 'symbol': 'Q', 'midi': 69},
#     'CAG': {'name': 'Glutamine', 'symbol': 'Q', 'midi': 69},
#     'CGT': {'name': 'Arginine', 'symbol': 'R', 'midi': 69},
#     'CGC': {'name': 'Arginine', 'symbol': 'R', 'midi': 69},
#     'CGA': {'name': 'Arginine', 'symbol': 'R', 'midi': 69},
#     'CGG': {'name': 'Arginine', 'symbol': 'R', 'midi': 69},
#     'ATT': {'name': 'Isoleucine', 'symbol': 'I', 'midi': 60},
#     'ATC': {'name': 'Isoleucine', 'symbol': 'I', 'midi': 60},
#     'ATA': {'name': 'Isoleucine', 'symbol': 'I', 'midi': 60},
#     'ATG': {'name': 'Methionine', 'symbol': 'M', 'midi': 69},
#     'ACT': {'name': 'Threonine', 'symbol': 'T', 'midi': 64},
#     'ACC': {'name': 'Threonine', 'symbol': 'T', 'midi': 64},
#     'ACA': {'name': 'Threonine', 'symbol': 'T', 'midi': 64},
#     'ACG': {'name': 'Threonine', 'symbol': 'T', 'midi': 64},
#     'AAT': {'name': 'Asparagine', 'symbol': 'N', 'midi': 65},
#     'AAC': {'name': 'Asparagine', 'symbol': 'N', 'midi': 65},
#     'AAA': {'name': 'Lysine', 'symbol': 'K', 'midi': 67},
#     'AAG': {'name': 'Lysine', 'symbol': 'K', 'midi': 67},
#     'AGT': {'name': 'Serine', 'symbol': 'S', 'midi': 62},
#     'AGC': {'name': 'Serine', 'symbol': 'S', 'midi': 62},
#     'AGA': {'name': 'Arginine', 'symbol': 'R', 'midi': 69},
#     'AGG': {'name': 'Arginine', 'symbol': 'R', 'midi': 69},
#     'GTT': {'name': 'Valine', 'symbol': 'V', 'midi': 64},
#     'GTC': {'name': 'Valine', 'symbol': 'V', 'midi': 64},
#     'GTA': {'name': 'Valine', 'symbol': 'V', 'midi': 64},
#     'GTG': {'name': 'Valine', 'symbol': 'V', 'midi': 64},
#     'GCT': {'name': 'Alanine', 'symbol': 'A', 'midi': 74},
#     'GCC': {'name': 'Alanine', 'symbol': 'A', 'midi': 74},
#     'GCA': {'name': 'Alanine', 'symbol': 'A', 'midi': 74},
#     'GCG': {'name': 'Alanine', 'symbol': 'A', 'midi': 74},
#     'GAT': {'name': 'Aspartate', 'symbol': 'D', 'midi': 71},
#     'GAC': {'name': 'Aspartate', 'symbol': 'D', 'midi': 71},
#     'GAA': {'name': 'Glutamate', 'symbol': 'E', 'midi': 74},
#     'GAG': {'name': 'Glutamate', 'symbol': 'E', 'midi': 74},
#     'GGT': {'name': 'Glycine', 'symbol': 'G', 'midi': 69},
#     'GGC': {'name': 'Glycine', 'symbol': 'G', 'midi': 69},
#     'GGA': {'name': 'Glycine', 'symbol': 'G', 'midi': 69},
#     'GGG': {'name': 'Glycine', 'symbol': 'G', 'midi': 69},
# }